apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tdarr
  namespace: media
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: coma-artichoke-network-https
  hostnames:
    - tdarr.coma.artichoke.network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tdarr-master
          port: 8265
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tdarr-server
  namespace: media
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: tdarr-tcp
  rules:
    - backendRefs:
        - name: tdarr-master
          port: 8266
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tdarr-webui
  namespace: media
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: tdarr-web-tcp
  rules:
    - backendRefs:
        - name: tdarr-master
          port: 8265