apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-auth
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-auth
  data:
    - secretKey: username
      remoteRef:
        key: authentik/postgres-auth
        property: username
    - secretKey: password
      remoteRef:
        key: authentik/postgres-auth
        property: password