apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-oidc-auth
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: autobrr-oidc-auth
  data:
    - secretKey: username
      remoteRef:
        key: autobrr/oidc-auth
        property: username
    - secretKey: password
      remoteRef:
        key: autobrr/oidc-auth
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-oidc-auth
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: autobrr-oidc-auth
  data:
    - secretKey: username
      remoteRef:
        key: autobrr/oidc-auth
        property: username
    - secretKey: password
      remoteRef:
        key: autobrr/oidc-auth
        property: password