apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-postgres-auth
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: autobrr-postgres-auth
  data:
    - secretKey: username
      remoteRef:
        key: autobrr/postgres-auth
        property: username
    - secretKey: password
      remoteRef:
        key: autobrr/postgres-auth
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-oidc-auth
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: autobrr-oidc-auth
  data:
    - secretKey: client-id
      remoteRef:
        key: autobrr/oidc-auth
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: autobrr/oidc-auth
        property: client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-session-secret
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: autobrr-session-secret
  data:
    - secretKey: session-secret
      remoteRef:
        key: autobrr/session-secret
        property: session-secret
