apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./namespace.yaml
  # - ./navidrome.yaml
  # - ./pv.yaml
  # - ./pvc.yaml
  # - ./ingress.yaml
  # - ./secrets.yaml
namespace: navidrome
