apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcpjungle
  namespace: ai
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: coma-artichoke-network-https
  hostnames:
    - mcpjungle.coma.artichoke.network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mcpjungle
          port: 8080
