apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml
      - home.yml
    options:
      disableNameSuffixHash: true
  - name: glance-user-css
    files:
      - user.css
    options:
      disableNameSuffixHash: true
namespace: glance