apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml
  - name: glance-config-home
    files:
      - home.yml
  - name: glance-user-css
    files:
      - user.css
namespace: glance