apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
  - ./ks.yaml
  # - ./app/helmrelease.yaml
  # - ./app/httproute.yaml]

configMapGenerator:
  - name: glance-config
    behavior: replace
    files:
      - ./app/config/glance.yml