apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: ${ACME_EMAIL}
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      # ArtichokeMC Cloudflare account
      - selector:
          dnsZones:
            - artichokemc.net
            - onkaparingait.com
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-artichokemc
              key: token
            email: services@artichokemc.net

      # Main Cloudflare account
      - selector:
          dnsZones:
            - artichoke.cc
            - nikolaipatrick.com
            - artichokenetwork.com
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: token
            email: ${ACME_EMAIL}
