apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.yaml
  - ./pv.yaml
  - ./pvc.yaml
  - ./ingress.yaml
  # - ./immich.yaml
  - ./httproute.yaml
