apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      version: 11.0.1
  interval: 1m0s
  values:
    service:
      ssh:
        type: LoadBalancer
        clusterIP: ""
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        server:
          ROOT_URL: https://git.artichoke.cc/
          START_SSH_SERVER: true
          SSH_DOMAIN: git-ssh.artichoke.cc
        mailer:
          PROTOCOL: smtps
          SMTP_ADDR: ${NOREPLY_EMAIL_HOST}
          SMTP_PORT: 465
          USER: ${GITEA_EMAIL}
          PASSWD: ${GITEA_EMAIL_PASS}
          FROM: ${GITEA_EMAIL}
        APP_NAME: "Artichoke's Gitea Server"
        database:
          DB_TYPE: postgres
          HOST: main-postgres-v2-rw.databases.svc.cluster.local
          NAME: gitea
          USER: gitea
          PASSWD: ${GITEA_POSTGRES_PASS}
          SCHEMA: public
        cache:
          ADAPTER: redis
          HOST: redis://main.redis-clusters.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
        queue:
          TYPE: redis
          CONN_STR: redis://main.redis-clusters.svc.cluster.local:6379/0
        service:
          DISABLE_REGISTRATION: true
        openid:
          ENABLE_OPENID_SIGNUP: true
