apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slskd-api-key
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slskd-api-key
  data:
    - secretKey: key
      remoteRef:
        key: slskd/api-key
        property: key
---