apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
  - ./security-policy.yaml

  - ./bazarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./autobrr/ks.yaml
  - ./tdarr/ks.yaml
  - ./unmanic/ks.yaml
  - ./profilarr/ks.yaml
  - ./qui/ks.yaml
  - ./soulbeet/ks.yaml
