apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-oidc-auth
  namespace: media
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qui-oidc-auth
  data:
    - secretKey: client-id
      remoteRef:
        key: qui/oidc-auth
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: qui/oidc-auth
        property: client-secret