apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weatherbus-ttn-ingestor
  namespace: weatherbus-ttn-ingestor
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  interval: 1m0s
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            env:
              MQTT_HOST: "au1.cloud.thethings.network"
              MQTT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: weatherbus-ttn-ingestor-mqtt-auth
                    key: username
              MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: weatherbus-ttn-ingestor-mqtt-auth
                    key: password
              MQTT_TOPIC: "v3/openclimate@ttn/devices/+/up"
              MQTT_USE_AUTH: true
              TTN_MQTT_PROTOCOL: "mqtts"
              TTN_MQTT_PORT: "8883"

              PG_DSN:
                valueFrom:
                  secretKeyRef:
                    name: weatherbus-ttn-ingestor-db-auth
                    key: url
            image:
              repository: sha256-8e7dbb31859390d0e193fcd31f2cff53ecfd1b3a7a7eb8ba16fdf6448bba8935.sig
              tag: master
              pullPolicy: IfNotPresent
