apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: onkaparingait
  namespace: onkaparingait
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: onkaparingait-root
  hostnames:
    - onkaparingait.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: onkaparingait
          port: 80
