apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja-mysql-auth
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-mysql-auth
  data:
    - secretKey: username
      remoteRef:
        key: invoiceninja/mysql-auth
        property: username
    - secretKey: password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: password
