apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lidarr
  namespace: flux-system
spec:
  image: ghcr.io/linuxserver-labs/prarr
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
  filterTags:
    pattern: '^lidarr-plugins-(?P<maj>\d+)\.(?P<min>\d+)\.(?P<patch>\d+)\.(?P<build>\d+)$'
    extract: "$maj.$min.$patch-$build"
  policy:
    semver:
      range: ">=3.0.0-0 <4.0.0-0"
