apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: onkaparingait
  namespace: flux-system
spec:
  image: ghcr.io/artichoked1/onkaparingait-ssg
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: onkaparingait
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: onkaparingait
  filterTags:
    pattern: '^build-(?P<build>[0-9]+)$'
    extract: '$build'
  policy:
    numerical:
      order: asc