apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  image: vaultwarden/server
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: 1.34.x
