apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-postgres-auth
  namespace: openwebui
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-postgres-auth
  data:
    - secretKey: username
      remoteRef:
        key: openwebui/postgres-auth
        property: username
    - secretKey: password
      remoteRef:
        key: openwebui/postgres-auth
        property: password
    - secretKey: url
      remoteRef:
        key: openwebui/postgres-auth
        property: url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-oidc-auth
  namespace: openwebui
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openwebui-oidc-auth
  data:
    - secretKey: client-id
      remoteRef:
        key: openwebui/oidc-auth
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: openwebui/oidc-auth
        property: client-secret
