apiVersion: v1
kind: ConfigMap
metadata:
  name: php-memory
  namespace: invoiceninja
data:
  99-memory.ini: |
    memory_limit = 512M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: invoiceninja
data:
  invoiceninja.conf: |
    # https://nginx.org/en/docs/http/ngx_http_core_module.html
    client_max_body_size 10M;
    client_body_buffer_size 10M;
    server_tokens off;

    # https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html
    fastcgi_buffers 32 16K;

    # https://nginx.org/en/docs/http/ngx_http_gzip_module.html
    gzip on;
    gzip_comp_level 2;
    gzip_min_length 1M;
    gzip_proxied any;
    gzip_types *;
  laravel.conf: |
    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html/public;

        index index.php;
        charset utf-8;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_pass 127.0.0.1:9000;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }