apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: invoiceninja
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  interval: 1m0s
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: invoiceninja/invoiceninja-debian
              tag: latest
            env:
              TZ: Australia/Adelaide
              APP_ENV: production
              APP_DEBUG: "false"
              APP_URL: https://invoiceninja.onkaparingait.com
              APP_KEY:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-app-key
                    key: app-key
              DB_HOST: invoiceninja-mariadb
              DB_DATABASE: invoiceninja
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-mysql-auth
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-mysql-auth
                    key: mariadb-password
              CACHE_DRIVER: redis
              QUEUE_CONNECTION: redis
              SESSION_DRIVER: redis
              REDIS_HOST: main.redis-clusters.svc.cluster.local
              REDIS_PASSWORD: "null"
              REDIS_PORT: 6379
              FILESYSTEM_DISK: debian_docker
              PDF_GENERATOR: snappdf
              TRUSTED_PROXIES: '*'
              PHANTOMJS_PDF_GENERATION: false
              IN_USER_EMAIL:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-initial-user
                    key: email
              IN_USER_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: invoiceninja-initial-user
                    key: password

    service:
      main:
        controller: main
        ports:
          http:
            port: 9000
    persistence:
      data:
        storageClass: "openebs-hostpath"
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/www/html/public
          - path: /var/www/html/storage
          - path: /var/www/html/storage/framework/sessions
          - path: /var/www/html/storage/framework/views
          - path: /var/www/html/storage/framework/cache
      php-memory:
        enabled: true
        type: configMap
        name: php-memory
        advancedMounts:
          main:
            main:
              - path: /usr/local/etc/php/conf.d/99-memory.ini
                subPath: 99-memory.ini
                readOnly: true
