apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja-app-key
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-app-key
  data:
    - secretKey: app-key
      remoteRef:
        key: invoiceninja/app-key
        property: app-key