apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja-app-key
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-app-key
  data:
    - secretKey: app-key
      remoteRef:
        key: invoiceninja/app-key
        property: app-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja-initial-user
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-initial-user
  data:
    - secretKey: email
      remoteRef:
        key: invoiceninja/initial-user
        property: email
    - secretKey: password
      remoteRef:
        key: invoiceninja/initial-user
        property: password