apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: invoiceninja
spec:
  interval: "1h"
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invoiceninja-mariadb
  namespace: invoiceninja
spec:
  chart:
    spec:
      chart: mariadb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: invoiceninja
      version: 24.0.2
  interval: 1m0s
  values:
    auth:
      createDatabase: true
      database: invoiceninja
      username: invoiceninja
      existingSecret: invoiceninja-mysql-auth
    primary:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: longhorn
