apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoiceninja-mysql-auth
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-mysql-auth
  data:
    - secretKey: username
      remoteRef:
        key: invoiceninja/mysql-auth
        property: username

    - secretKey: mariadb-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mariadb-password

    - secretKey: mariadb-root-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mariadb-root-password

    - secretKey: mariadb-replication-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mariadb-replication-password
