apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoiceninja-mysql-auth
  namespace: invoiceninja
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoiceninja-mysql-auth
  data:
    - secretKey: username
      remoteRef:
        key: invoiceninja/mysql-auth
        property: username

    - secretKey: mysql-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mysql-password

    - secretKey: mysql-root-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mysql-root-password

    - secretKey: mysql-replication-password
      remoteRef:
        key: invoiceninja/mysql-auth
        property: mysql-replication-password
