apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: 2025.2.4
  interval: 1m0s
  values:
    worker:
      env:
        - name: TMPDIR
          value: /tmp
    authentik:
      bootstrap_token: test
      bootstrap_password: test
      secret_key: ${AUTHENTIK_SECRET_KEY}
      error_reporting:
        enabled: true
      email:
        host: ${NOREPLY_EMAIL_HOST}
        port: 465
        username: ${NOREPLY_EMAIL}
        password: ${NOREPLY_EMAIL_PASS}
        use_tls: false
        use_ssl: true
        from: ${NOREPLY_EMAIL}
      postgresql:
        host: authentik-postgres-rw.databases.svc.cluster.local
        name: authentik
        user: authentik
        password: ${AUTHENTIK_POSTGRES_PASS}
        port: 5432
      redis:
        host: main.redis-clusters.svc.cluster.local
    server:
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
    global:
      volumes:
        - name: custom-css
          configMap:
            name: authentik-custom-css
      volumeMounts:
        - name: custom-css
          mountPath: /web/dist/custom.css
          subPath: custom.css
