apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.yaml
  - ./authentik.yaml
  # - ./ingress.yaml
  - ./css-configmap.yaml
  - ./httproute.yaml
