apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-env-vars
  namespace: glance
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: glance-env-vars
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: glance/env-vars
