apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unmanic
  namespace: media
spec:
  parentRefs:
    - name: web-gateway
      namespace: networking
      sectionName: coma-artichoke-network-https
  hostnames:
    - unmanic.coma.artichoke.network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: unmanic
          port: 8888