apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-media-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: unmanic-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-cache-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: unmanic-cache-pv
